# Generated by Django 3.0.4 on 2020-05-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20200517_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Use'},
        ),
    ]
