# Generated by Django 3.0.4 on 2020-05-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20200518_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
