# Generated by Django 3.0.4 on 2020-05-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_auto_20200518_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
