# Generated by Django 3.0.4 on 2020-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
