# Generated by Django 3.0.4 on 2020-05-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0019_auto_20200518_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
